# Generated by Django 3.0.3 on 2020-11-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanceInfo', '0002_deployinstance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mirageInstance',
            new_name='DeployedInstance',
        ),
        migrations.DeleteModel(
            name='DeployInstance',
        ),
    ]
