# Generated by Django 3.0.3 on 2020-11-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanceInfo', '0003_auto_20201121_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeployedInstance',
            new_name='DeployedInstances',
        ),
    ]
