# Generated by Django 3.0.3 on 2020-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanceInfo', '0004_auto_20201121_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployedinstances',
            name='moduleType',
            field=models.CharField(choices=[('FMV', 'FMV'), ('GSM', 'GSM')], max_length=10),
        ),
    ]
