# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.33.11"

    config.vm.provision "shell", inline: <<-SHELL
     echo ==== VM Provisioning occuring in `pwd` on `hostname`==========
     yum update
     yum install -y net-tools
     yum install -y bind-utils-9.9.4-72.el7.x86_64

     echo ==== installing java,wget,etc ==========
     yum install -y java
     yum install -y wget
     echo ==== jenkins: installing ==========
     mkdir work; cd work
     wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
     rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
     yum install -y jenkins

     echo ==== jenkins: starting ==========
     systemctl start jenkins.service
     systemctl -l status jenkins.service
     echo
     echo ==== jenkins: console key ==========
     echo ==== Next: Now go to http://192.168.33.11:8080/
     echo ====       This will force /var/lib/jenkins/secrets/initialAdminPassword
     echo ====       to be generated

   SHELL
end
